_target_: src.models.bitsave_metricgan_proxy_module.BitSaveLitModule
optimizer_g:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

optimizer_d:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler_g:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 12
  gamma: 0.5

scheduler_d:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 12
  gamma: 0.5

generator:
  _target_: src.models.components.asconvsr.AsConvSR
  hidden_channels: 64
  E: 3
  temperature: 30 # useless
  ratio: 4
  global_residual: false

discriminator:
  _target_: src.models.components.metric_discriminator.MetricDiscriminator
  kernel_size: [5, 5]
  base_channels: 15

proxy:
  _target_: src.models.components.JPEG_proxy.encode_decode_intra.EncodeDecodeIntra
  min_qstep: 1

augmentation:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandomCrop
      size: [256, 256]
      pad_if_needed: true
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.v2.RandomVerticalFlip
      p: 0.5
    - _target_: torchvision.transforms.v2.ToDtype
      dtype:
        _target_: hydra.utils.get_object
        path: torch.float32
      scale: true

gan_loss_weight: 0.01
rate_weight: 1
un_compress_weight: 0.01
