_target_: src.models.bitsave_module.BitSaveLitModule
lambda1: 0
lambda2: 0
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.bitsave.BitSave
  hiddden_channels: 12
  num_blocks: 4
