_target_: src.models.with_FVC_module.WithFVCLitModule
train_lambda: 0.01
train_gamma: 0.1
FVC_model_path: "/mnt/md1/user_wayne/PyTorchVideoCompression/FVC/snapshot/8192.model"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.85
  threshold: 0.0025
  patience: 0

net:
  _target_: src.models.components.bitsave.BitSave
  hiddden_channels: 12
  num_blocks: 4
